-- Create History Table
create table if not exists history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id text not null,
  title text,
  artist text,
  thumbnail text,
  played_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table history enable row level security;

create policy "Users can insert their own history"
  on history for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own history"
  on history for select
  using (auth.uid() = user_id);

-- Create Favorites Table
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id text not null,
  title text,
  artist text,
  thumbnail text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, video_id)
);

alter table favorites enable row level security;

create policy "Users can manage their favorites"
  on favorites for all
  using (auth.uid() = user_id);

-- Create Playlists Table
create table if not exists playlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table playlists enable row level security;

create policy "Users can manage their own playlists"
  on playlists for all
  using (auth.uid() = user_id);

-- Create Playlist Items Table
create table if not exists playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint references playlists on delete cascade not null,
  video_id text not null,
  title text,
  artist text,
  thumbnail text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table playlist_items enable row level security;

-- Policy for playlist items: check if the parent playlist belongs to the user
create policy "Users can manage items in their own playlists"
  on playlist_items for all
  using (
    exists (
      select 1 from playlists
      where playlists.id = playlist_items.playlist_id
      and playlists.user_id = auth.uid()
    )
  );

-- Enable Realtime for these tables
alter publication supabase_realtime add table favorites;
alter publication supabase_realtime add table playlists;
alter publication supabase_realtime add table playlist_items;
